name: validate nix expression
on:
  pull_request:
    branches: ["main"]


jobs:
  validate-nix-expression:
    name: validate nix expression
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v15
      with:
        name: tkt-cache
    -  run: sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
    - run: nix flake check     .  --no-build

