name: build kernel with Nix
on:
  workflow_call:
      inputs:
        kernel_attribute:
          type: string
          required: true
      secrets:
        CACHIX_AUTH_TOKEN:
          required: true
  workflow_dispatch:
    inputs:
      kernel_attribute:
        type: string
        required: true


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v15
      with:
        name: tkt-cache
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}" #
    -  run: sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
    - run: nix build    --print-build-logs .#${{inputs.kernel_attribute}}

