name: Build Kernel with Nix

on:
  workflow_call:
    inputs:
      # You can add inputs here if you want to parameterize the build,
      # for example, to change the kernel version or flake attribute.
      kernel_attribute:
        description: 'The flake attribute to build (e.g., linux_6_15-tkt)'
        required: true
        type: string
      tkt_cache_name:
        description: 'The name of the cachix cache to push to'
        required: true
        type: string

jobs:
  build-with-nix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          # This enables Flakes and the new command syntax
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Configure Cachix
        # This step uses your Cachix authentication token to allow pushing to your private cache.
        # You must configure the CACHIX_AUTH_TOKEN secret in your repository settings.
        uses: cachix/cachix-action@v15
        with:
          name: ${{ inputs.tkt_cache_name }}
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build Kernel with Nix and Push to Cachix
        # This is the core step that runs your specified command.
        # It builds the kernel attribute from your GitLab repo and pipes the output path
        # directly to 'cachix push' to upload the build artifacts.
        run: |
          nix build --no-link --print-build-logs --print-out-paths "gitlab:suan5553/tkt-kernel-test-build#${{ inputs.kernel_attribute }}" | cachix push ${{ inputs.tkt_cache_name }}
